### ISSUE TITLE
Use Sinon + Chai instead of Mockery?

### ISSUE THREAD

**Issue by zckrs** [yeoman/generator-node#166]

**Comment by sindresorhus** [comment]
Can you be more clear? The description field is there for a reason ;)

Do you want us to switch to Sinon+Chai or do you want to know how to do that in your project? If the former, include arguments for why.

**Comment by SBoudrias** [comment]
Node.js assertions are plenty enough for any test case. They're easily portable to any other projects. That's why we don't use `chai` (too complex IMO).

About Sinon vs Mockery, both of them don't do the same thing. We'd use both if we had a use case for sinon, but in currently we only need mockery.

**Comment by zckrs** [comment]
Thank you @SBoudrias for answer.
